site_name: Documentation Template
# フッターにコピーライトを追加
copyright: "&copy; 2023 YumaMatsumura"
# 右上にGitリポジトリのリンクを追加
repo_url: https://github.com/YumaMatsumura/DocumentationTemplate
repo_name: YumaMatsumura/DocumentationTemplate
nav:
  - Template: index.md
theme:
  name: material
  font:
    text: Noto Sans JP
    code: Inconsolata
  icon:
    repo: fontawesome/brands/github # repo_url, repo_nameで設定したアイコン
  palette:
    primary: teal  # テーマカラー
  features:
    - content.code.copy # コードコピーボタンの追加
    - navigation.top # ドップに戻るボタンの追加
plugins:
  search:
    lang: 'ja' # 日本語検索の有効化
extra:
  social: # フッターにアイコン&リンクを追加
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/A69eZhrYLmCWncr
    - icon: fontawesome/brands/github
      link: https://github.com/YumaMatsumura/DocumentationTemplate
  generator: false # フッターにMkDocsで生成されたことを非表示にする
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - admonition # メモ、ヒント、警告などのブロックの有効化
  - attr_list # ボタンの有効化
  - footnotes # 注釈の有効化
  - pymdownx.arithmatex: # 数式拡張機能の有効化
      generic: true
  - pymdownx.details # メモ、ヒント、警告などの折りたたみブロックの有効化
  - pymdownx.highlight: # コードハイライトの有効化
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.keys # キーコードの有効化
  - pymdownx.smartsymbols # シンボル（コピーライトなど）の有効化
  - pymdownx.superfences: # コードフェンスの有効化
      custom_fences:
        - name: mermaid  # コードフェンスにmermaid機能を追加
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # タブブロックの有効化
      alternate_style: true
  - pymdownx.tasklist: # タスクリストの有効化
      custom_checkbox: true
      clickable_checkbox: true
